// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataLakePath():Promise<string>;

export function GetDataLakeStatus():Promise<string>;

export function GetEmailFileCount():Promise<number>;

export function GetEmailPath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListEmailFiles(arg1:number):Promise<Array<string>>;
