// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateZip(arg1:main.CreateZipRequest):Promise<main.CreateZipResponse>;

export function GetDataLakePath():Promise<string>;

export function GetDataLakeStatus():Promise<string>;

export function GetEmailFileCount():Promise<number>;

export function GetEmailPath():Promise<string>;

export function GetOperationalMode():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListEmailFiles(arg1:number):Promise<Array<string>>;

export function SearchFiles(arg1:main.FileSearchRequest):Promise<main.FileSearchResult>;
