// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataLakePath() {
  return window['go']['main']['App']['GetDataLakePath']();
}

export function GetDataLakeStatus() {
  return window['go']['main']['App']['GetDataLakeStatus']();
}

export function GetEmailFileCount() {
  return window['go']['main']['App']['GetEmailFileCount']();
}

export function GetEmailPath() {
  return window['go']['main']['App']['GetEmailPath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListEmailFiles(arg1) {
  return window['go']['main']['App']['ListEmailFiles'](arg1);
}
