// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCategories():Promise<Record<string, number>>;

export function GetFileCount():Promise<number>;

export function GetFiles(arg1:Array<string>):Promise<Array<Record<string, any>>>;

export function GetProductionRequests():Promise<Array<main.ProductionRequest>>;

export function Greet(arg1:string):Promise<string>;
