// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetFileCount() {
  return window['go']['main']['App']['GetFileCount']();
}

export function GetFiles(arg1) {
  return window['go']['main']['App']['GetFiles'](arg1);
}

export function GetProductionRequests() {
  return window['go']['main']['App']['GetProductionRequests']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
